= GraphQL Song
:toc:

image:https://github.com/Softsapiens/graphql-song/workflows/Rust/badge.svg[]

== Abstract

This is a wip link:https://www.rust-lang.org/[Rust] project for link:https://graphql.org[GraphQL] learning.

== Tech-Stack

The project used technologies/principal libs are following:

* link:https://www.rust-lang.org/[Rust] (stable)
* link:https://docs.rs/hyper/0.13.5/hyper/[Hyper]
* link:https://docs.rs/juniper/0.14.2/juniper/[Juniper]
* link:https://docs.rs/elasticsearch/7.7.0-alpha.1/elasticsearch/[Elasticsearch-rs]
* link:https://www.elastic.co/elasticsearch/[Elasticsearch]

=== Local play

Play Elasticsearch locally as follows:

`docker run -d --name elasticsearch -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.6.1`

Play the server via:

`cargo run`

Request could be made either by using some external tool like link:https://insomnia.rest/[insomnia] with the provided link:./insomnia[requests]
Or by using the internal included link:http://localhost:3000/graphiql[GraphIQL].


== Load Testing / Benchmarking

Install link:https://artillery.io[artillery.io] as a benchmark cli tool.

=== Post request

The test is link:./performance/graphql-song-load.yml[here].

```
artillery run ./performance/graphql-song-load.yml
```
See some results in a HP-Zbook G4 laptop, requesting one Human object using 500 reqs/sec during 10 seconds:

```
All virtual users finished
Summary report @ 17:19:57(+0200) 2020-05-14
  Scenarios launched:  5000
  Scenarios completed: 5000
  Requests completed:  5000
  Mean response/sec: 474.83
  Response time (msec):
    min: 1.3
    max: 49.6
    median: 2.3
    p95: 6.9
    p99: 9.3
  Scenario counts:
    0: 5000 (100%)
  Codes:
    200: 5000
```

== References

=== GraphQL to be or not to be

. https://medium.com/@JeffLombardJr/when-and-why-to-use-graphql-24f6bce4839d
. https://blog.logrocket.com/5-reasons-you-shouldnt-be-using-graphql-61c7846e7ed3/

=== Specification

. https://graphql.org/learn/

=== Server internals

. https://www.apollographql.com/blog/graphql-explained-5844742f195e
. https://www.howtographql.com/advanced/1-server/

=== Real use-cases

. https://hasura.io/docs/1.0/graphql/manual/index.html
. https://netflixtechblog.com/graphql-search-indexing-334c92e0d8d5

=== Aggregations

. https://hasura.io/docs/1.0/graphql/manual/queries/aggregation-queries.html